### ISSUE TITLE
在win7系统上运行客户端报错，是不支持win7系统吗？

### ISSUE THREAD

**Issue by leonoing** [galaxy-s10/billd-desk-electron#1]
When running the client on win7 system, an error is reported. Is win7 system not supported?
在win7系统上运行客户端报错，是不支持win7系统吗？ 
试了64位和32位都会报相同的错误
错误：无法定位程序输入点DiscardVirtualMemory于动态链接库KERNEL32.dll上。
![微信图片_20241031144034](https://github.com/user-attachments/assets/6182e07d-a53a-48f3-a2d3-a822a5ec6c67)

**Comment by galaxy-s10** [comment]
> When running the client on win7 system, an error is reported. Is win7 system not supported? 在win7系统上运行客户端报错，是不支持win7系统吗？ 试了64位和32位都会报相同的错误 错误：无法定位程序输入点DiscardVirtualMemory于动态链接库KERNEL32.dll上。 ![微信图片_20241031144034](https://private-user-images.githubusercontent.com/48108597/381852384-6182e07d-a53a-48f3-a2d3-a822a5ec6c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MjQ5MTgsIm5iZiI6MTczMDQyNDYxOCwicGF0aCI6Ii80ODEwODU5Ny8zODE4NTIzODQtNjE4MmUwN2QtYTUzYS00OGYzLWEyZDMtYTgyMmE1ZWM2YzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAxMzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMjFmM2NjM2JhMDcyYWJhOWUxYjZmYjM3YTdiNDcxYTNlMWM0OTYxMTdiNTY1Yjk2Y2Q3MzliMWU4MmMzY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8D4NlYgqdPucOZ-K60fL_HtSySR5lbLhOTe8vnaqseU)

没有win7系统，没测试过，可以拉项目到本地，本地运行起来看看报什么错
